### PR TITLE
Decompress gzip files

### LINKED ISSUE #2090: Gzipped files are producing empty folders or not getting extracted
Tested on OS X 10.11 and Windows 10, using Bower 1.7.0.

When running `bower install --save path/to/agzipped.js.gz`, bower either creates an empty folder with the name of the file (Mac) or creates a folder but does not extract the file, resulting in `bower_components\package\index.gz`. (Windows) The same thing happens when the dependency is manually added to `bower.json` and `bower install` is run.

- The behavior is always the same, including the difference between both platforms
- It happens with local files as well (`bower install --save ../a-nice-file.js.gz`)

The issue where `index.gz` is created was already mentioned in #1004, the issue where the file is extracted, then treated as a folder is not documented anywhere. At any rate, Bower does not seem to handle purely gzipped files –as oppossed to tar.gz– very well.

I am writing tests for tar extraction right now, after that I can look into why gz extraction is failing, or maybe someone else wants to look into it?

### PR DESCRIPTION
**Pull request by Utsav2**
Update request lib.

This fixes #2090 and #1004, but I'm not sure how to unit test it.

I tried it with the example given in #1004 

`bower install --save-dev hellosign=http://s3.amazonaws.com/cdn.hellofax.com/js/embedded.js`

and it works.

In short, if request notices a gzipped file, it decompresses it. We need to add the option there because request doesn't do it automatically (for backward compatibility reasons).

### CODE REVIEW

**Comment by accommodavid** [comment]
:+1: Nice work!

**Comment by contolini** [comment]
Nice job!

Some testing thoughts: Reply headers can be specified with [nock](https://www.npmjs.com/package/nock#specifying-reply-headers). Try adding a test to `test/util/download.js` that mocks the downloading of a text file with a `'Content-Encoding': 'gzip'` header. After it's downloaded, if you can successfully read its contents with `fs.readFileSync`, the test passes and satisfies #1004.

For #2090, use the same test as above but add `.gz` to the end of the text file.

If you need any help, find us on [chat](https://discord.gg/0fFM7QF0KpZRh2cY).

**Comment by Utsav2** [comment]
@contolini Thanks for the tips. Just to clarify, I should add a gzipped file to tests/assets and test against that, right?

**Comment by sheerun** [comment]
@Utsav2 Yes, you can use nock's "replyWithFile" helper and .txt file encoded with gzip you put in `test/assets`.

**Comment by Utsav2** [comment]
@sheerun How does it look now?

**Comment by sheerun** [comment]
LGTM :)

**Pull request merged**
