### PR TITLE
postuninstall hook feature

### PR DESCRIPTION
**Pull request by royka**
```postuninstall``` hook for bower

See the original issue here https://github.com/bower/bower/issues/1451

Any and all feedback welcome!

### CODE REVIEW

**Comment by pertrai1** [comment]
@royka Can you check the failing build for your test?

**Comment by royka** [comment]
@pertrai1 Taken a look but I can reproduce the failing build, I've tried running the test suite with different node versions but can't see why the test fails in Travis

**Comment by faceleg** [comment]
@royka did you run it with node 4.2?

**Comment by royka** [comment]
ran it on node version 4.2.2 on OS X as well as 5.0. Just run grunt test right?

**Comment by royka** [comment]
just ran the tests on ubuntu:12.04 image with node version 4.2 test still passed

**Comment by royka** [comment]
also ran on windows 10 with node 5.0, maybe I'm missing something?

**Comment by sheerun** [comment]
Maybe it's some kind of race condition? ..

**Comment by sheerun** [comment]
@royka You need to wrap `scripts.postuninstall` in another function, just like here: https://github.com/royka/bower/blob/postuninstall-hook-feature/lib/core/Project.js#L109

That's how promises work.

Please also rebase on current master branch and force push changes. Thank you!

**Comment by sheerun** [comment]
Also, please add another test instead of modifying existing one :)

**Comment by royka** [comment]
Thanks @sheerun will update with the changes!

**Comment by royka** [comment]
Pushed the changes suggested test pass locally so waiting for CI to come back but all feedback is welcome, wanted and very much needed :)

**Comment by sheerun** [comment]
Unfortunately some Travis builds are still failing :) Also, could you squash all commits when they pass?

**Comment by royka** [comment]
Will get to work on this soon, sorry to leave it hanging!

**Comment by sheerun** [comment]
Hey. Any progress?

**Comment by sheerun** [comment]
Commited in #2252

**Pull request closed without merging**
