### PR TITLE
Use yargs instead of deprecated optimist

### PR DESCRIPTION
**Pull request by guyathomas**
Issue: Prototype pollution issue with the version of minimalist that optimist is using https://github.com/mgol/check-dependencies/issues/41

Fix: Use `yargs` - "the modern, pirate-themed successor to optimist". With the same API for our limited usage. ( And a tonne of community support )

### CODE REVIEW

**Comment by locks** [comment]
I just chased a security warning down the depredency tree that lead me to this PR. This change would be very helpful for ember-cli!

**Comment by sheerun** [comment]
ok I'll handle this right after I merge #2554

**Comment by sheerun** [comment]
Unfortunately I cannot accept this PR as tests are failing for node <= 6 and Bower is committed to backward compatiblity

**Comment by sheerun** [comment]
This issue should be fixed in bower-config 1.4.2

**Pull request closed without merging**
