### PR TITLE
Run travis tests in all versions of node

### PR DESCRIPTION
**Pull request by faceleg**

### CODE REVIEW

**Comment by faceleg** [comment]
Don't see how this reduced coverage?

**Comment by sheerun** [comment]
@faceleg Let's not care about coverage too much :)

**Comment by faceleg** [comment]
:+1: 

How reliable is appveyor? I don't think I've seen a PR that had a successful appveryor build yet

**Comment by sheerun** [comment]
Since we shrinkwrapper all the dependencies, not so much. I'll try to install newest npm on appveyor...

**Comment by watilde** [comment]
@sheerun I've tried to re-do shrinkwrap again with lates npm but that seems another reason..
https://github.com/bower/bower/pull/2028

**Pull request merged**
