### PR TITLE
update package.json dependencies

### LINKED ISSUE #1622: Update dependencies
[Some of them](https://david-dm.org/bower/bower#info=dependencies&view=table) are really out of date.

<bountysource-plugin>

---
Want to back this issue? **[Place a bounty on it!](https://www.bountysource.com/issues/6828854-update-dependencies?utm_campaign=plugin&utm_content=tracker%2F91759&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F91759&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by laurelnaiad**
Update dependencies in package.json to (mostly) latest available
versions.

Updating these dependencies removes warnings when bower is installed
as a devDependency in other packages and keep the code fresh.

Methodology:

- `npm install`
- `npm test` (all tests pass)
- `npm-check-updates -u`
- `npm test` (find errors, suspect semver, back off to `~2.3.0` in
package.json)
- `rm -rf node_modules` (and .gitignored files)
- `npm install`
- `npm test` (all pass, deem updated version compatible)
- revert to package.json from `master`
- `npm install` (install the old dependencies)
- switch back to updated package.json
- `npm install` (upgrade dependencies in place)
- `npm test` (all tests still pass, deem upgrades safe)

As to the `semver` dependency, it seems that updating to 4.x requires
handling breaking changes, which is TODO.

Closes #1622

### CODE REVIEW

**Comment by laurelnaiad** [comment]
There's nothing especially magical about this, I just thought that if the legwork was holding up updates, I could do that. :)

**Comment by ilanbiala** [comment]
@laurelnaiad big updates, nice job!

**Comment by sheerun** [comment]
Don't forget to release :)

**Comment by laurelnaiad** [comment]
I for one think this might want to cook in master for a little while. Lots of code changes underneath this....

**Pull request merged**
