### PR TITLE
ignoredDependencies tests

### PR DESCRIPTION
**Pull request by twalpole**
This adds high level install and update tests to PR #1394

### CODE REVIEW

**Comment by twalpole** [comment]
@sheerun Updated to pull ignoredDependencies from .bowerrc rather than bower.json

**Comment by samccone** [comment]
@twalpole this looks like it needs a rebase on top of master

**Comment by twalpole** [comment]
@samccone ugh -- it was good 2 days ago - I guess there have been updates since then - on it

**Comment by samccone** [comment]
great thanks a bunch. @sheerun knows way more about the requirements than I here so I defer to him

**Comment by sheerun** [comment]
It seems OK, I've rebased it one more time and merged it to master

**Comment by nmccready** [comment]
This looks like the sha that resolved this bf23d81c9ee005c950f602237886e0730e2a844c , adding for traceability .

**Pull request closed without merging**
