### PR TITLE
Bug/pull zip from cache 1945 rewrite

### PR DESCRIPTION
**Pull request by smali-kazmi**
Rewrite fix for https://github.com/bower/bower/issues/1945

### CODE REVIEW

**Comment by smali-kazmi** [comment]
@sheerun thank you so much for your guidance; will write failing test in my free time

**Comment by smali-kazmi** [comment]
@sheerun please review this PR thanks

**Comment by sheerun** [comment]
@smali-kazmi The test you've added is passing even without your change.

It needs to be failing test: fails before your change, and passes after your change.

**Comment by smali-kazmi** [comment]
@sheerun actual bug was when zip file is updated bower detected there is change in zip file due to eTag; but problem was that; bower just check version inside of bower.json file; if that version exist in cache use it; and what i did is that i just attached eTag with version no. so if version is not updated and eTag is updated create a folder in cache like [version no]:[eTag]; and use it to update component folder; and wrote test case against it; 

Test cases are passing because none of the case contains `_release: '123',`; 

if still it is not suffice then please provide me a concrete example of test; you required to accept this PR;

Thanks

**Comment by sheerun** [comment]
In the test you need to fetch package 2 times, each time with different `_release`. You need to test that second time, the cache of previous package is not used.

Currently you just test that you the package is downloaded and extracted, not that it changed.

**Comment by sheerun** [comment]
Could you also rebase your branch on current Bower's master branch? There are tests fixed in `master`.

**Comment by sebnor** [comment]
What is the current status of this PR? We're affected by the #1945 bug and would love to see this PR merged.

**Comment by sheerun** [comment]
Closing as bower is deprecated and not developed anymore, plus allowing for changing contents of packages seems seems like a bad idea given package locking being more popular e.g. in Yarn

**Pull request closed without merging**
