### PR TITLE
Allow `@` to be used as a divider with cli: install and info.

### PR DESCRIPTION
**Pull request by wookoouk**
`@` is replaced with `#` as part of the `info` and `install` commands.

### CODE REVIEW

**Comment by wookoouk** [comment]
is the appveyer branch test working? it has not reported on the last 4-5 PRs *Waiting for status to be reported*

**Comment by sheerun** [comment]
I'm not sure. I've reset appveyor authentication, maybe it'll work next time.

For now I've merged manually. Great work! :)

**Comment by wookoouk** [comment]
Awesome, send another my way please.

**Comment by sheerun** [comment]
@wookoouk Could you maybe handle https://github.com/bower/bower/pull/2263 ? We need to make sure bower won't hang for old git versions (that don't support GIT_TERMINAL_PROMPT)

**Comment by sheerun** [comment]
(it's the only task that blocks next release)

**Comment by wookoouk** [comment]
On it

**Comment by mscottx88** [comment]
I have confirmed version 1.8.0 does not allow for installing from a git URL.  downgrading to 1.7.9 resolves this problem.

**Pull request merged**
