### PR TITLE
Implement postuninstall hooks with tests

### PR DESCRIPTION
**Pull request by oskarcieslik**
Implements feature from #1451.

### CODE REVIEW

**Comment by oskarcieslik** [comment]
I know somebody already pushed PR with this but mine passes tests and I want this feature in bower :)

**Comment by sheerun** [comment]
Could you create new test instead modifying existing one?

**Comment by oskarcieslik** [comment]
Sure! working on it

**Comment by oskarcieslik** [comment]
Btw, any idea why tests are not running on my PRs @sheerun?

**Comment by sheerun** [comment]
I think there were permission issues with travis, should be fixed now

**Pull request merged**
