### PR TITLE
Displaying info message when user login via bower login

### PR DESCRIPTION
**Pull request by rajzshkr**
Currently, we don't show any message when logged in via bower login.
In this pull request, I have shown an info message like,

bower EAUTH Logged in as username

I have used bower logger for showing the info message.

### CODE REVIEW

**Comment by rajzshkr** [comment]
Gave pull request as single commit.

**Comment by sheerun** [comment]
You don't need to create another PR. You can just `git push --force`.

Can you add message when someone logins with login/password instead of authkey?

**Comment by rajzshkr** [comment]
Added info message for both login, via normal and 2 factor auth mode.

**Comment by sheerun** [comment]
There's a CI error to fix:

Running "jshint:files" (jshint) task
 
   lib\commands\install.js
     11 |        return;
                 ^ Unreachable 'return' after 'throw'.
 
>> 1 error in 105 files

**Comment by rajzshkr** [comment]
oops.. I will resolve the issue and will give again.

**Comment by rajzshkr** [comment]
It is already merged by @azbshiri

**Pull request closed without merging**
