### PR TITLE
Bump bower-json to ^0.6.0

### PR DESCRIPTION
**Pull request by cvrebert**
~~This is temporarily blocked on https://github.com/bower/json/pull/27#issuecomment-123874284~~

### CODE REVIEW

**Comment by sheerun** [comment]
I've heard extra errors make it backward-incompatible. No?

**Comment by cvrebert** [comment]
It does enforce the `bower.json` spec more strictly (https://github.com/bower/json/pull/26).

**Comment by cvrebert** [comment]
The build now passes (after futzing with the package names used in the testcases) since `bower-json@0.6.0` has been published on npm.

**Comment by faceleg** [comment]
LGTM /cc @sheerun

**Comment by sheerun** [comment]
@faceleg Doesn't it break backward compatibility? For example are you able to install and register non-compatible packages that are already present in registry? We need to test this first..

**Comment by sheerun** [comment]
already done

**Pull request closed without merging**
