### PR TITLE
Bug/pull zip from cache 1945

### PR DESCRIPTION
**Pull request by smali-kazmi**
https://github.com/bower/bower/issues/1945

### CODE REVIEW

**Comment by paulohp** [comment]
@smali-kazmi Thanks for your contribution!

I'm seeing some tests failing on both Travis and AppVeyor with NODE_VERSION=0.10.x. 

Can you take a look?

Thanks.

**Comment by sheerun** [comment]
@paulohp Those tests fail on master branch as well... We need to fix them there ASAP

**Comment by mudaser-caremerge** [comment]
@paulohp for me locally in node v0.12.0 all test are passing;

**Comment by smali-kazmi** [comment]
@paulohp i had run test locally but in node v0.12.0; all tests were passing;

**Comment by smali-kazmi** [comment]
@sheerun i will try to install node v0.10 locally and test it; currently following test are failing

````
1) resolverFactory should recognize registry endpoints correctly:
     Error: timeout of 30000ms exceeded. Ensure the done() callback is being called in this test.
  
  2) resolverFactory should error out if the package was not found in the registry:
     Uncaught Error: socket hang up
      at createHangUpError (http.js:1473:15)
      at CleartextStream.socketCloseListener (http.js:1523:23)
      at tls.js:694:10
  3) resolverFactory "after each" hook:
     Uncaught Error: socket hang up
      at createHangUpError (http.js:1473:15)
      at CleartextStream.socketOnEnd [as onend] (http.js:1569:23)
      at CleartextStream.onCryptoStreamEnd (tls.js:323:24)
      at _stream_readable.js:944:16
````

**Comment by sheerun** [comment]
As I said, it's not your fault here. Tests are failing on master, and we need to debug them..

**Comment by sheerun** [comment]
It's probably connected to nock mocking http requests

**Comment by sheerun** [comment]
@smali-kazmi OK, I've pushed the fix to master. Could you try to rebase this PR on master branch?

**Comment by sheerun** [comment]
And force push, of course

**Comment by sheerun** [comment]
Also, I think overriding the cache is a bad idea (we've got concurrency issues because of it in the past). Instead we probably should use different cache directory.

So the fix should be modify `_getPkgRelease` so it returns different release for different zips.

(e.g. use `pkgMeta._release` instead of `pkgMeta._target`, if it exists).

Hope it helps :) Also, could you prepare a failing test as well?

**Comment by paulohp** [comment]
oh I see @sheerun :+1:

**Comment by smali-kazmi** [comment]
@sheerun thanks for the help and tip i had start working on it;

**Comment by smali-kazmi** [comment]
I am closing this PR because i had created new PR #2026

**Pull request closed without merging**
