### PR TITLE
Fix bug unauthenticated git protocol in GitHubResolver

### PR DESCRIPTION
**Pull request by Edufreitass**
Hello guys, there is a discussion of this issue opened by @oliverfoster in #2611, browse there for more details =)

### CODE REVIEW

**Review by fabioebt — APPROVED** [review]
ok, great! Thank you.

**Review by anderson-mordhorst — APPROVED** [review]

**Review by MoisesDuarte — APPROVED** [review]

**Comment by MoisesDuarte** [comment]
thank your for the fix!

**Comment by rayanmarcus** [comment]
Excellent this suggestion!

**Comment by sheerun** [comment]
Thank you, I'll test and release very soon

**Comment by oliverfoster** [comment]
How is this going?

**Comment by oliverfoster** [comment]
Any news on this?

**Pull request merged**
