### PR TITLE
Extend conflict message

### PR DESCRIPTION
**Pull request by echavezNS**
I think that just by clarifying the statement we could avoid some confusions as in #1714.

### CODE REVIEW

**Comment by BenMann** [comment]
Just a slight typo.. it should be plural: numbers.
Other than that, LGTM! :dancer:

**Comment by echavezNS** [comment]
Done :)

**Comment by BenMann** [comment]
Btw, for such small changes as the typo you could always `git commit --amend` or `rebase -i`. For larger PRs with more commits people will ask you to squash those (9 and 10 in the [contrib guidelines](https://github.com/bower/bower/blob/master/CONTRIBUTING.md)). Thx for the PR ;)

**Comment by echavezNS** [comment]
@BenMann Thank's for the advice, I will do next time :)

**Pull request merged**
