### PR TITLE
Lock fs-write-steam-atomic to 1.0.5

### LINKED ISSUE #2118: ENOENT file or directory does not exist, rename in 1.7.1
Getting an ENOENT for a non existent .tar.gz in the bower cache on Windows 7

### PR DESCRIPTION
**Pull request by samccone**
context: https://github.com/bower/bower/issues/2118#issuecomment-168097858

Fixes #2118

----

much :cake: to @kbenjamin for being a champ helping to bisect this.. A++++ work

---

xref https://github.com/npm/fs-write-stream-atomic/issues/11

### CODE REVIEW

**Comment by samccone** [comment]
cc @sheerun @bower/committers 

The current release of bower (1.7.1) is broken by this, so any :eyes: are appreciated thanks!

**Comment by vladikoff** [comment]
@samccone can you repush the commit to see if the appveyor failure is related. otherwise looks good

**Comment by vladikoff** [comment]
@samccone actually the main build passed, so merging..

**Comment by vladikoff** [comment]
I'll push out a new release...

**Comment by samccone** [comment]
thanks @vladikoff

**Comment by iarna** [comment]
Yeah, unfortunately `fs-write-stream-atomic@latest` was broken for two days in december (12/10-12/12), but it was fixed with 1.0.8 at 2015-12-12T06:55:11.674Z, so I'm not sure why anyone would still be seeing references to the bad versions?

Regardless, I've marked 1.0.6 and 1.0.7 as deprecated, so that this is made clear.

**Comment by sheerun** [comment]
@iarna It's because we use bundledDependencies in bower, just like npm does.

**Pull request merged**
