### PR TITLE
support GitHub-style namespacing (org/repo) for bower register

### PR DESCRIPTION
**Pull request by fewspider**
for #1857

### CODE REVIEW

**Comment by mohsen1** [comment]
It's already possible to install via org/repo syntax. I would assume you can reuse the convert url logic from that instead of writing your own `convertGitUrl`

**Comment by fewspider** [comment]
@mohsen1 thanks your suggestion,I found install via org/repo is only available the repo in github,but repo is not only in github,maybe it is in `bitbucket`,my solution is fetching the first remote address that the list of `git remote -v`

**Comment by sheerun** [comment]
A test, please :)

**Comment by sheerun** [comment]
Superseded by #2248

**Pull request closed without merging**
