### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by eduardoervideira**
Update README.md - Translated to Portuguese.

### CODE REVIEW

**Comment by samccone** [comment]
is there a best practice on how to handle this?

**Comment by eduardoervideira** [comment]
I'm trying to help ... It was really bad? If you don't want, sorry.

2015-04-03 21:36 GMT+01:00 Sam Saccone <notifications@github.com>:

**Comment by eduardoervideira** [comment]
Hey, was it bad? I didn't get it if you don't want my help or whatever...
Did I something wrong?

**Comment by samccone** [comment]
Hi @eduardoervideira your translated the whole readme to Portuguese. That means everyone who would look at the readme would see it in Portuguese. I do not that that is what we want. 

I am not sure if there is a best practice for internationalization of github readmes. I have yet to see anyone doing it.

I am going to close for now, if anyone (@sheerun ) has any thoughts  I would love to hear them,

Thanks for the work regardless @eduardoervideira

**Pull request closed without merging**
