### PR TITLE
Add `bower update --save` functionality 

### LINKED ISSUE #2035: Bower doesn't update bower.json still
This might have been asked before, but, why ```bower update --save``` doesn't update bower.json? Or what is the right way to update the dependencies to the latest version?

### PR DESCRIPTION
**Pull request by contolini**
This PR lets `bower update` update `bower.json` via a `--save` flag. It mimics [npm's update behavior](https://docs.npmjs.com/cli/update#recording-updates-with-save).

Current behavior:

- `bower update` updates components in `bower_components/` while respecting components' semver in `bower.json`. For example, if bootstrap is listed as `~2.2.0` in `bower.json`, running `bower update` will update `bower_components/bootstrap` to 2.2.2 because 2.2.2 is the latest version greater than 2.2.0 but less than 3.0.0.
- `bower.json` is not modified.
- Here are [steps to test this behavior locally](https://gist.github.com/contolini/c950b513f37aa6e754d2).

New behavior proposed by this PR:

- `bower update --save` does the same stuff above but it also edits `bower.json`. In the above example, bootstrap would now be listed in `bower.json` as `~2.2.2`.
- `bower update --save-dev` works the same but for dev dependencies.
- Extraneous dependencies (components that exist in `bower_components/` but aren't listed in `bower.json`) are ignored.

See #2035 and #1468.

@bower/contributors please review. Feedback is appreciated.

### CODE REVIEW

**Comment by sheerun** [comment]
Looks promising :) Could you squash the commits and force-push them?

**Comment by contolini** [comment]
@sheerun Definitely. Is AppVeyor failing because of this PR? Or is it just having a bad day?

**Comment by sheerun** [comment]
Yes, appveyor is failing because of timeout on one test. Maybe you need to use nock to mock some connection or something (optionally increase maximum timeout for this test).

Don't look at node 0.10 on appveyor because it's failing for unrelated issues..

**Comment by contolini** [comment]
Cool, for now I just increased the timeout for that test file. I'll look into properly mocking the http requests when I get some more time. There are other `update` issues I'd like to tackle (esp. #256).

**Comment by sheerun** [comment]
Should I wait until you add tests for updating a single package?

**Comment by colinodell** [comment]
+1

**Comment by contolini** [comment]
@sheerun No, unfortunately that bug (#256) is a complicated one. If y'all are okay with the code in this PR, I think it's ready to be merged.

**Comment by sheerun** [comment]
Thank you

**Comment by feniixx** [comment]
I've just runned  `npm install bower -` & `bower update --save` and the depencies are updated, but `bower.json` isn't updated, I mean the depency version doesn't change

**Comment by sheerun** [comment]
It will be released as bower 1.6.9

**Comment by feniixx** [comment]
Oh, ok

**Pull request merged**
