### PR TITLE
Alt npm load

### PR DESCRIPTION
**Pull request by jisaacks**
@sheerun this is the alternate implementation I was purposing in #1735 I think it is much cleaner. I feel like there might have been some confusion in what I was describing so I just created a seperate pull request here to demonstrate.

I feel like this one pretty cleanly solves the problem.

### CODE REVIEW

**Comment by jisaacks** [comment]
@samccone, @sheerun is there any interest in this feature anymore? 

I know it was originally [green-lighted](https://github.com/bower/bower/issues/1731#issuecomment-78205375) then I was told the first implementation [changed too much](https://github.com/bower/bower/pull/1735#issuecomment-97696663). I think this new implementation is pretty clean while not alternating much existing code. 

If this feature is no longer wanted I will be happy to close the PRs and Issue and delete my fork. If it is still on the table I would be willing to squash and rebase my commits and also try to figure out why the tests are failing (I currently have no idea why) but I do not want to continue working on this if it isn't going to be looked at. 

Let me know, thanks.

**Comment by sheerun** [comment]
Yes, it's still on the table.. I just have little free time,

**Comment by jisaacks** [comment]
@sheerun thanks. I can understand the lack of time, I suffer the same problem :)

Also did some refactoring to put all the logic in a single promise chain and have the tests passing.

Let me know if there is anything else.

**Comment by jisaacks** [comment]
Anyone care to give me the :+1: on merging this?

**Comment by sheerun** [comment]
I'll merge it right away, but I'm afraid after you rebase on master, you'll need to fix the tests (e.g. private flag should be present in bower.json).

**Comment by jisaacks** [comment]
@sheerun rebased and fixed.

**Comment by jisaacks** [comment]
@sheerun ping

**Comment by sheerun** [comment]
@jisaacks I've squashed changes and merged to master. You you very much!

**Comment by jisaacks** [comment]
No problem! Glad to pitch in when and where I can :)

**Pull request closed without merging**
