### PR TITLE
Vendor ext-name (drop meow dependency)

### PR DESCRIPTION
**Pull request by sheerun**

### CODE REVIEW

**Comment by snakamura** [comment]
@sheerun This PR made bower unusable when I installed bower via npm. isAsset.js tried to load ext-name package instead of loading it from lib/vendor, but ext-name was not installed because it was no longer included in package.json.

**Comment by sheerun** [comment]
sorry about that I'll fix it

**Comment by sheerun** [comment]
0.8.3 should be fixed

**Comment by snakamura** [comment]
Thanks!

**Pull request merged**
