### PR TITLE
Lock lru-cache package

### PR DESCRIPTION
**Pull request by vladikoff**
@sheerun r?

### CODE REVIEW

**Comment by sheerun** [comment]
I'm for it, but I can't release right now. Maybe you want to do it?

**Comment by vladikoff** [comment]
> I'm for it, but I can't release right now. Maybe you want to do it?

I cannot push to npm. What help do you need with the release?

**Comment by sheerun** [comment]
I've just added you to release managers.

Just please make sure public installation of bower still works after release :)

**Comment by vladikoff** [comment]
> I've just added you to release managers.
> Just please make sure public installation of bower still works after release :)

Okay thanks, I shall fix this up

**Comment by vladikoff** [comment]
* Ignoring AppVeyour failure, happens in `master`, will need to fix this separately

**Comment by sheerun** [comment]
@vladikoff Could you update changelog on master branch?

**Comment by vladikoff** [comment]
Done, thanks!

**Pull request merged**
