### PR TITLE
Remove @ in temporary directories

### LINKED ISSUE #1650: When using svn with bower and temp dir has @ the repo is not fetched correctly
When I fetch a bower package, it is stored at a temp dir.
In some cases, the computer's username may have an @. 
In this case, the generated temp dir will contain this @, making svn act weird.

For example, in Windows, if I have "example@example.com" as username, generated temp dir will be:
```` C:\Users\EXAMPLE~1.COM\AppData\Local\Temp\PC-EX-example@example.com\bower\PACKAGE-NAME-XXXX ````

SVN interprets the @ on this uri as something else and it crops it to:
```` C:\Users\EXAMPLE~1.COM\AppData\Local\Temp\PC-EX-example ````

Storing the data somewhere else. Then, when bower tries to read and copy the files, it throws an error

I'm making a PR for fix this issue

### PR DESCRIPTION
**Pull request by Utsav2**
Should fix #1650

### CODE REVIEW

**Comment by sheerun** [comment]
Can you write a test to confirm it?

**Comment by sheerun** [comment]
Maybe it would be better to mp5 the `_name`?

**Comment by Utsav2** [comment]
1) What do you mean by mp5? Are you saying that I should run the replace() only on  _name instead of the entire path?

2) I've written a test to check that the '@' character is not preserved in directory name. What else should the test check?

**Comment by sheerun** [comment]
1) Use md5 hash of this._name instead of this._name itself
2) It should be ok

**Comment by Utsav2** [comment]
I've made the change, let me know if I should squash both the commits together

**Comment by sheerun** [comment]
Looks good. Thank you! :)

**Pull request merged**
