### PR TITLE
Implements jscs to enforce a newly created style guide for the repo.

### PR DESCRIPTION
**Pull request by AnthonyBobsin**
Also uses jscs to fix some minor style guide warnings.

### CODE REVIEW

**Comment by AnthonyBobsin** [comment]
Directly related to issue #2043

**Comment by sheerun** [comment]
Hey. This PR is non-mergable. Could you rebase it to master branch of bower?

**Comment by sheerun** [comment]
I think we can put "bower-style-guide.md" to Wiki and only link it from CONTRIBUTING.md

**Comment by AnthonyBobsin** [comment]
Ah sorry about that, I rebased from my local master by accident.

Tried to rebase from current master, and it seems that there are tests failing due to the most recent commit d2ba80e6e97b13483bf113514ec1e6d1b8f8a03f. Should I still just rebase with that and submit? I can wait until those tests are resolved.

I included a page in the Wiki as well. I can just remove the `docs/bower-style-guide.md` file completely if you like. The reason I left the file was just in case something happened to the wiki page, since it seems as people can just go in and edit (which isn't bad). It probably wouldn't be feasible in the future to maintain both sources though

**Comment by sheerun** [comment]
> Should I still just rebase with that and submit? 

Yes, please :)

> I included a page in the Wiki as well.

For now I've enabled public editing of wiki, but I'll enable it for contributors-only soon. I'd rather link to documents instead of put them into repository. Besides Wiki has history :)

**Comment by AnthonyBobsin** [comment]
Rebased and removed style guide file from repo. Should be all good to go :)

**Comment by faceleg** [comment]
Why not ESLint?

**Comment by AnthonyBobsin** [comment]
@faceleg - I chose JSCS because we currently use JSHint, and coding-style related rules we used from JSHint are deprecated. For all these rules that are deprecated, JSHint recommended using JSCS. Now we are using JSHint to take care of coding correctness, while JSCS takes care of coding style. I go into this briefly in the new style guide.

**Comment by faceleg** [comment]
Makes sense, thanks for being patient with the question :)

**Comment by sheerun** [comment]
Really awesome, thank you :)

**Pull request merged**
