### PR TITLE
Added abbreviation for 'update'

### PR DESCRIPTION
**Pull request by pertrai1**
Started to explore the update command in more detail and 
started here for easier use of the update command

### CODE REVIEW

**Comment by sheerun** [comment]
@pertrai1 level:beginner tags are supposed for something to be done, not something done.

In `bower up` works well with current installation and is unambiguous (we also have uninstall and unregister commands).

**Comment by pertrai1** [comment]
@sheerun Maybe I am looking in the wrong places for the abbreviations but I don't see one that is for running `bower update`? Still getting around the code base so I apologize if I was not looking in the right place for all of the abbreviations.

**Comment by pertrai1** [comment]
@sheerun `bower up` is for updating bower not for running an `update` for the dependencies. Do you not think that an abbreviation for updating dependencies is needed?

**Comment by sheerun** [comment]
`bower up` is the same as `bower update`. that's how abbrev module works.

**Comment by feniixx** [comment]
Does this mean that we can use either `bower u --save` or `bower up --save` to update our all our dependencies to the latest version inside `bower.json` ?

**Comment by sheerun** [comment]
`bower u --save` is too short because abbrev package doesn't know whether to match it to `update` or `unregister`. But you can use `bower up --save`, yes. And no, it won't update all the dependencies to latest versions. See #2035

**Pull request closed without merging**
