### PR TITLE
Adding reset cli functionality

### PR DESCRIPTION
**Pull request by imjacobclark**
As discussed in #1596, this PR adds functionality to reset dependencies by removing them, clearing cache and then updating dependencies. 

Feedback please? :smile:

### CODE REVIEW

**Comment by craigmingtaozhang** [comment]
:+1:

**Comment by ain** [comment]
Works like a charm, just tested.

@sindresorhus any chance for this to be reviewed and merged?

**Comment by sindresorhus** [comment]
I'm not involved here anymore.

**Comment by ain** [comment]
@sindresorhus thanks, but could you tag the reviewers for attention please?

**Comment by samccone** [comment]
@imjacobclark would you be able to rebase this? or @ain are you interested in picking up this PR and opening a new PR

**Comment by davidyezsetz** [comment]
+1

**Comment by imjacobclark** [comment]
@samccone I'll rebase this, no worries.

**Comment by CarloMatic** [comment]
+1

**Comment by ain** [comment]
@imjacobclark it has diverged, you're missing `readOptions()` on a command so it throws up. Needs to be added.

**Comment by imjacobclark** [comment]
@ain cheers I'll take a look shortly

**Comment by ain** [comment]
@imjacobclark please push in the `templates/helpers/json/help-reset.json` as well. Something like:

```json
{
    "command": "reset",
    "description": "The reset functionality allows developers to easily reinstall the packages.\n\nUsing 'bower reset' in a project folder will remove all installed packages and install them again.",
    "usage": [
        "reset"
    ],
    "options": [
        {
            "shorthand":   "-h",
            "flag":        "--help",
            "description": "Show this help message"
        }
    ]
}
```

**Comment by imjacobclark** [comment]
@ain @samccone rebased, fixed diverged code. good to go?

**Comment by imjacobclark** [comment]
Is this likely to get merge in? @sheerun @samccone

**Comment by ain** [comment]
I think the coverage shouldn't actually drop over the added feature, so I'd presume there're some tests missing?

**Comment by sheerun** [comment]
Maybe we incorporate this command as a flag to `install`? As far as I know if we pass `--force` flag, then cache reads are skipped. We only need to make sure packages are re-installed properly.

I think in your case you also remove extraneous packages (not present in bower.json), while they should be preserved. There are no tests as well.

My vote is to improve `install` command instead introducing new one.

**Comment by ain** [comment]
I like the `--force` flag idea.

**Comment by sheerun** [comment]
Unfortunately Bower is not developed anymore and we don't accept new features

**Pull request closed without merging**
