### PR TITLE
Feature/deplinks

### PR DESCRIPTION
**Pull request by sheerun**
Rebased version of #833 

I cleaned it up and removed unlinking part as it's unnecessary and introduce more moving parts.

For a second I wanted introduce `--config.deplinks` flag, but I think it can be the default.

### CODE REVIEW

**Comment by worldspawn** [comment]
Sorely need this, wheres the 1.4 milestone?

**Comment by sheerun** [comment]
changed to "minor release"

**Comment by gaurav21r** [comment]
@sheerun is this done? Any status update if not? I guess this branch can be merged into 1.6.x ?

**Comment by yelly** [comment]
What needs to be done for this to make it in to the next version? I might be able to help as this seems to solve a pretty common issue.

**Comment by sheerun** [comment]
Unfortunately Bower is not developed anymore and we don't accept new features, closing this

**Pull request closed without merging**
