### PR TITLE
Components that are not installed by bower should be left alone

### PR DESCRIPTION
**Pull request by adewinter**
This is a rework of PR #1363  with changes as requested.   I was unable to simply build on top of @wibblymat's  commit because I was unable to get the full suite of tests to pass despite much tweaking and debugging.  With the commit being ~200 commits behind master I decided it would be easier to create a new branch off of master and go from there, since most of the code ended up being rewritten for this fix.

Please let me know if there are any additional changes needed!

Thanks,
Anton

### CODE REVIEW

**Comment by sheerun** [comment]
I think we can ignore `--force` flag and let user know about `bower prune` command.. Hm?

**Comment by sheerun** [comment]
Actually I'm not 100% what `prune` does, so better check that :)

**Comment by jisaacks** [comment]
Doesn't prune remove all installed packages that are not in the bower.json?

**Comment by adewinter** [comment]
I felt like --force was the way to go here. If you don't want the default behavior ("skip this folder/component") you can *force* bower to blow the folder away and reinstall the component... Seems in line with what it normally does?

**Comment by breen-cengage** [comment]
@jisaacks that's my understanding re: prune -- not sure it'd be useful in this scenario

**Comment by sheerun** [comment]
Rebased and commited to master

**Pull request closed without merging**
