### PR TITLE
Code of conduct for contributors

### PR DESCRIPTION
**Pull request by pertrai1**

### CODE REVIEW

**Comment by sheerun** [comment]
We should probably put it in wiki or website instead, as it applies to all bower repositories, and I don't want to pollute repository with extra docs. Hm?

**Comment by pertrai1** [comment]
Yeah I have it on the wiki so we don't need it in the repo if it would clog it up.

**Comment by sheerun** [comment]
We can link it from CONTRIBUTING.md, though

**Comment by pertrai1** [comment]
I think that this line is enough to get the person to see the Code of Conduct:

    There is more information about contributing in the Wiki.

**Pull request closed without merging**
