### PR TITLE
Allow the info command to accept @ as a divider

### PR DESCRIPTION
**Pull request by wookoouk**
replace @ with # when the endpoint is received

### CODE REVIEW

**Comment by wookoouk** [comment]
The tricky bit is writing the tests ;)

**Comment by sheerun** [comment]
Could you cover other commands as well before we merge? :)

**Comment by wookoouk** [comment]
Sure, just need to figure out a good way to test `bower install
package@version` then I will re merge.

**Comment by sheerun** [comment]
I've created dummy empty package: https://github.com/sheerun/empty

Maybe something like this will work?

```
        return helpers.run(install, [
            ['empty@1.0.1'], {
                save: true
            }
        ]).then(function () {
            ...
        });
```

**Comment by wookoouk** [comment]
Cheers, now tidying up my changes and putting a new merge in

**Comment by wookoouk** [comment]
replaced with merge: https://github.com/bower/bower/pull/2322

**Pull request closed without merging**
