### PR TITLE
Supports ~/ paths to cwd field in .bowerrc

### LINKED ISSUE #1784: Support ~/ paths for user home in .bowerrc
I work on a team that is sharing .bowerrc files since we are using an internal registry however there is no way to specify storage paths (cache/registry) in a way that works for all users without supporting `~/path`.

Currently anything that begins with a `~` will create a directory called `~` inside the project instead of inside the user's home directory.

### PR DESCRIPTION
**Pull request by watilde**
Updates:
+ Add untildify module
+ Update config.js to convert tilde path to home path

Fixes #1784

### CODE REVIEW

**Comment by sheerun** [comment]
Could you write a test for it?

**Comment by watilde** [comment]
Sure thing!

**Comment by watilde** [comment]
@sheerun Done! Could you please see again?

**Comment by sheerun** [comment]
Looks good, thank you! :)

**Pull request merged**
