### PR TITLE
[WIP] Shrinkwrap feature

### PR DESCRIPTION
**Pull request by sheerun**
This is WIP PR, do not merge. <strike>You can send any work against this branch (even not fully working). It will be squashed at the end.</strike> Please start work from master branch and send PR to master branch.

---

As mentioned in #505:
1. Lock file is named `bower.lock`
2. Lock file contains concatenated `.bower.json` files generated by bower (some subset of their keys)
3. On production bower installs non-development packages using endpoints from `bower.lock`
4. After installation it compares every `.bower.json` with entry in `bower.lock`. If something doesn't  match, then source tampering is assumed, and the installation is immediately aborted.
5. For now the `_resolution` entry in `.bower.json` should be enough to prevent source tampering (as @schmurfy pointed out it's impossible to change source without changing sha of commit).
6. If in future we decide to implement full hashing, we'll just add it to `.bower.json` (there is no chicken-egg problem because `.bower.json` is generated by bower, not stored in source control).

For anyone who doesn't know how `.bower.json` looks like, [here is a sample](https://gist.github.com/sheerun/10695384). The keys that begin with underscore are added by bower. All other keys come from `bower.json` of component.

### CODE REVIEW

**Comment by tmikoss** [comment]
Eagerly awaiting this feature - lack of it is proving to be a roadblock of adoption in my team.

**Comment by atipugin** [comment]
+1 Version locking would be very useful

**Comment by Wirone** [comment]
+1

This is crucial, from my perspective it does not make sense without version locking. When more than one person works on project and each of team members has own development environment, there are test and production instances, it's not acceptable to install packages without version consistency. It's best way to keep programmer's stereotype alive: "Works for me!" ;-)

Thanks in advance for implementing this feature, I'm looking forward for it!

**Comment by micahlmartin** [comment]
Have any pull requests with actual implementation been submitted against this yet?

**Comment by sheerun** [comment]
@micahlmartin Not yet

**Comment by karlingen** [comment]
+1

**Comment by hannahhoward** [comment]
if someone wants to implement this, is there pre-existing work that should be used, or is it enough to read the specs in the comments of this doc and start from bower#master?

**Comment by sheerun** [comment]
@hannahhoward Unfortunately there is no pre-existing work. bower#master is place to start.

I can support anyone who decides to implement it. Even give write access to bower.

**Comment by kodypeterson** [comment]
@sheerun I think I am going to take a stab at this over the weekend and see what I can come up with!

**Comment by sheerun** [comment]
Uh. Rebasing of this branch automatically closed this PR, and I can't reopen it.. Seems like a Github bug.

I'm going to create another issue with detailed documentation.

**Comment by mruoss** [comment]
Or just write to support an ask to reopen it?
Am 21.03.2015 05:09 schrieb "Adam Stankiewicz" <notifications@github.com>:

**Comment by andrewboni** [comment]
+1 for this - definitely needed for my team

**Comment by jfmercer** [comment]
:+1:

**Comment by karlingen** [comment]
@sheerun 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉

**Comment by sheerun** [comment]
I've reopened it because github fixed the issue, but mind real PR is here: #1747

**Comment by sheerun** [comment]
Bower is now deprecated and we recommend to use Yarn or Npm that support file locking.

Here's the guide how to migrate: https://bower.io/blog/2017/how-to-migrate-away-from-bower/

**Pull request closed without merging**
