### PR TITLE
fix passing options to request

### PR DESCRIPTION
**Pull request by pwielgolaski**
options from download need to be pass to request library that make HTTP
request

Also when there is http error stream need to be closed otherwise there
is issue reported that unlink operation is not permitted on Windows

### CODE REVIEW

**Comment by faceleg** [comment]
Would you please be able to add a test that confirms the "unlink" error occurred and has now been fixed?

**Comment by pwielgolaski** [comment]
Maybe I will find some time over weekend, but can not promise.
The most important is to start passing options to download is current implementation is useless behind corporate firewall

**Comment by pwielgolaski** [comment]
I added some test and small fix for handing error in download
Please review.

**Comment by faceleg** [comment]
Thanks @pwielgolaski @albertinad, @kodypeterson, @sheerun any issues with this being merged?

**Comment by pwielgolaski** [comment]
I would love to see this one in ;)

**Comment by faceleg** [comment]
Need another LGTM from @bower/bower-volunteers-write-access

**Comment by pertrai1** [comment]
@faceleg The diff looks good to me.

**Comment by faceleg** [comment]
Thanks @pertrai1, @pwielgolaski.

We're still working out the particulars of how to PR->merge->release with the new volunteers, but this will go out with the next release.

**Comment by sheerun** [comment]
@bower/bower-volunteers Please don't judge PRs by diff, but by actually testing it.

Also, as described in https://github.com/bower/bower/blob/master/CONTRIBUTING.md "Looks good to me" is not the same as "Ship it!". So let's merge when two of you actually test the PR and say "Ship it!".

"Looks good to me" is nice too, but I think it's not enough.

**Comment by pertrai1** [comment]
@sheerun I do agree and did test, and after that wanted to pass along the the diff looked good in regards to the changes made after passing. I agree with using Ship It!

**Comment by faceleg** [comment]
@sheerun noted, apologies

**Comment by sheerun** [comment]
Well, it turns out the Windows build were failing. I fixed it directly on fix/windows-appveyor branch..

We still need to fix tests for node 0.10...

**Pull request merged**
