### PR TITLE
(config)[Feature]: Add the possibility to set the shorthandResolver a…

### PR DESCRIPTION
**Pull request by TooHTooH**
Add the possibility to set the `shorthandResolver` falsy

### CODE REVIEW

**Comment by faceleg** [comment]
@sheerun is this a fairly common appveyor failure?

**Comment by TooHTooH** [comment]
Hello, this PR is link with https://github.com/bower/endpoint-parser/pull/11,
to be able to put sources like `feature/add-events` which contains `/`, cause I am using git flow,

Thank you

**Comment by sheerun** [comment]
@TooHTooH Why you find it useful?

**Comment by sheerun** [comment]
@TooHTooH I'd be happy to accept after there's a test for it :)

**Comment by sheerun** [comment]
Rebased as #2507

**Pull request closed without merging**
